language: csharp
solution: JPB.DataAccess.sln
sudo: required
env:
 global:
  - EnableNuGetPackageRestore=true 
install:
  - nuget restore JPB.DataAccess.sln
mono:
  - latest
script:
  - xbuild /p:Configuration=Release JPB.DataAccess.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./JPB.DataAccess/bin/Release/JPB.DataAccess.Tests.MsSQL.dll
