language: csharp
solution: JPB.DataAccess.sln
sudo: required
env:
 global:
  - EnableNuGetPackageRestore=true 
install:
  - nuget restore JPB.DataAccess.sln
mono:
  - latest
script:
  - xbuild JPB.DataAccess.sln
