//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPB.DataAccess.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbLoaderResouces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbLoaderResouces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPB.DataAccess.Tests.DbLoaderResouces", typeof(DbLoaderResouces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataContent&gt;
        ///  &lt;DatabaseScope&gt;
        ///    &lt;Types&gt;
        ///      &lt;Type Index=&quot;0&quot; Type=&quot;JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests.Book, JPB.DataAccess.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///      &lt;Type Index=&quot;1&quot; Type=&quot;JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests.Image, JPB.DataAccess.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/Types&gt;
        ///    &lt;Tables&gt;
        ///      &lt;Table Index=&quot;0&quot;&gt;
        ///        &lt;Book&gt;
        ///          &lt;BookId&gt;1&lt;/BookId&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BooksWithImagesDatabaseDump {
            get {
                return ResourceManager.GetString("BooksWithImagesDatabaseDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;DataContent&gt;
        ///  &lt;DatabaseScope&gt;
        ///    &lt;Types&gt;
        ///      &lt;Type Index=&quot;0&quot; Type=&quot;JPB.DataAccess.Tests.Users, JPB.DataAccess.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///      &lt;Type Index=&quot;1&quot; Type=&quot;JPB.DataAccess.Tests.Users, JPB.DataAccess.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/Types&gt;
        ///    &lt;Tables&gt;
        ///      &lt;Table Index=&quot;0&quot;&gt;
        ///        &lt;Users&gt;
        ///          &lt;User_ID&gt;1&lt;/User_ID&gt;
        ///          &lt;UserName /&gt;
        ///        &lt;/Users&gt;
        ///        &lt;Users&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UsersInDatabaseDump {
            get {
                return ResourceManager.GetString("UsersInDatabaseDump", resourceCulture);
            }
        }
    }
}
