//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests
{
	using JPB.DataAccess.DbInfoConfig.DbInfo;
	using JPB.DataAccess;
	using JPB.DataAccess.DbInfoConfig;
	using System;
	using System.Collections.Generic;
	using System.CodeDom.Compiler;
	using System.Linq;
	using System.Data;
	using JPB.DataAccess.ModelsAnotations;
	using JPB.DataAccess.AdoWrapper;

	public class UsersAutoGenerateConstructorWithMultiXml_Factory
	{
		[ObjectFactoryMethodAttribute()]
		public static JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests.UsersAutoGenerateConstructorWithMultiXml Factory(IDataRecord record)
		{
			JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests.UsersAutoGenerateConstructorWithMultiXml super;
			super = new JPB.DataAccess.Tests.TestModels.CheckWrapperBaseTests.UsersAutoGenerateConstructorWithMultiXml();
			super.User_ID = ((long)(record["User_ID"]));
			object username;
			username = record["UserName"];
			if ((username == System.DBNull.Value))
			{
				super.UserName = null;
			}
			else
			{
				super.UserName = ((string)(username));
			}
			object subs;
			subs = record["Subs"];
			if ((subs != System.DBNull.Value))
			{
				super.Subs = new DbCollection.NonObservableDbCollection<UsersAutoGenerateConstructorWithSingleXml>(
					XmlDataRecord.TryParse(((string)(subs)), 
					typeof(UsersAutoGenerateConstructorWithSingleXml), false)
					.CreateListOfItems()
					.Select(typeof(UsersAutoGenerateConstructorWithSingleXml)
					.GetClassInfo()
					.SetPropertysViaReflection));
			}
			return super;
		}
	}
}




namespace JPB.DataAccess.Tests
{
	using JPB.DataAccess.DbInfoConfig;
	using System;
	using System.Collections.Generic;
	using System.CodeDom.Compiler;
	using System.Linq;
	using System.Data;
	using JPB.DataAccess.ModelsAnotations;

	// Created by BORGCUBE\User
	// Created on 2016 April 30
	[GeneratedCodeAttribute("JPB.DataAccess.EntityCreator.MsSql.MsSqlCreator", "1.0.0.8")]
	public sealed partial class Users
	{
		public Users()
		{
		}
		private long _userID;
		public long UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		private string _userName;
		public string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		static partial void BeforeConfig();
		static partial void AfterConfig();
		static partial void BeforeConfig(ConfigurationResolver<Users> config);
		static partial void AfterConfig(ConfigurationResolver<Users> config);
		[ObjectFactoryMethodAttribute()]
		public static Users Factory(IDataRecord record)
		{
			Users super;
			super = new Users();
			super.UserID = ((long)(record["User_ID"]));
			object username;
			username = record["UserName"];
			if ((username == System.DBNull.Value))
			{
				super.UserName = null;
			}
			else
			{
				super.UserName = ((string)(username));
			}
			return super;
		}
		[ConfigMehtodAttribute()]
		public static void ConfigUsers(ConfigurationResolver<Users> config)
		{
			Users.BeforeConfig();
			Users.BeforeConfig(config);
			config.SetFactory(Users.Factory, true);
			config.SetPropertyAttribute(s => s.UserID, new ForModelAttribute("User_ID"));
			config.SetPropertyAttribute(s => s.UserID, new PrimaryKeyAttribute());
			Users.AfterConfig();
			Users.AfterConfig(config);
		}
	}
}
